name: CI
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types: approved
    branches:
      - master
    
jobs:
  np-build:
    if: github.ref == 'refs/heads/master' 
    runs-on: [self-hosted, linux, x64]
    environment: 'Development'
    env: 
         SUPER_SECRET: ${{ secrets.TEST_KEY }}  
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          env | grep SUPER
          echo $SUPER_SECRET
          echo Hello np, world ${{github.ref}} ! 
  prod-build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: [self-hosted, linux, x64]
    environment: 'Production'
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello prod, world ${{github.ref}} ${{secrets.TEST_KEY}}!
