name: CI
on:
  push:
    branches:
      - sample
    tags:
      - v* 
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello np, world ${{github.ref}}!
  np-build:
    if: github.ref == 'refs/heads/sample' 
    runs-on: [self-hosted, linux, x64]
    environment: 'Development'
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello np, world ${{github.ref}}!
  prod-build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: [self-hosted, linux, x64]
    environment: 'Production'
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello prod, world ${{github.ref}}!
