name: Test CICD
on:
  push:
    branches:
      - master
    tags:
      - v* 
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: update dependencies
        run: echo sample ${{github.ref}}
  store_artifacts:
    needs: build 
    runs-on: [self-hosted, linux, x64]
    environment: 'Development'
    steps:
      - name: store staging artifacts
        run: |
            test=img-phare-dev-rhel-$(date '+%Y-%m-%d-%H-%M') >> $GITHUB_ENV
            echo "action_state=img-phare-dev-rhel-$(date '+%Y-%m-%d-%H-%M')" >> $GITHUB_ENV
            echo $test done
      - name: sample
        run: |
           echo sample $test done
           echo "${{ env.test }}"
           echo "$action_state" test1
           echo "${{ env.action_state }}" test2
