name: Test CICD
on:
  push:
    branches:
      - master
    tags:
      - v* 
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: update dependencies
        run: echo sample ${{github.ref}}
  store_artifacts:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: store staging artifacts
        if: github.ref == 'refs/heads/master' 
        run: |
            mkdir -p /home/phare-dev/workspace/staging
            cp -R /home/phare-dev/actions-runner/_work/MyRepos/MyRepos /home/phare-dev/workspace/staging/
      - name: store prod artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
            mkdir -p /home/phare-dev/workspace/production
            cp -R /home/phare-dev/actions-runner/_work/MyRepos/MyRepos /home/phare-dev/workspace/production/
