name: CI
on:
  push:
    branches:
      - sample
    tags:
      - v* 
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello np, world {{github.ref}}!
  np-build:
    if: github.ref == 'ref/head/sample' 
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello np, world {{github.ref}}!
  prod-build:
    if: github.ref == 'ref/head/v*'
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello prod, world {{github.ref}}!
